- name: Installeer MySQL-server
  apt:
    name: "{{ mysql_package }}"
    state: present
    update_cache: yes
  notify: Restart MySQL  

- name: Maak een databasegebruiker aan
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "*.*:ALL"
    host: "%"
    state: present
  notify: Reload MySQL privileges
